CREATE DATABASE ASTRONOMIA;
CREATE TABLE CIALA_NIEBIESKIE(
	NAZWA CHAR(255) PRIMARY KEY,
	MASA FLOAT CHECK (MASA > 0),
	PROMIEN FLOAT CHECK (PROMIEN > 0),
	GESTOSC FLOAT CHECK (GESTOSC > 0),
	PRZYSPIESZNIE_GRAWITACYJNE FLOAT CHECK (PRZYSPIESZNIE_GRAWITACYJNE > 0),
	PERYCENTRUM FLOAT CHECK (PERYCENTRUM > 0),
	APOCENTRUM FLOAT CHECK (APOCENTRUM > 0),
	REKTASCENSJA FLOAT CHECK (REKTASCENSJA >= 0 AND REKTASCENSJA <=24),
	DEKLINACJA FLOAT CHECK (DEKLINACJA >= -90 AND DEKLINACJA <= 90),
	WIEK FLOAT CHECK (WIEK > 0),
	ODLEGLOSC FLOAT CHECK (ODLEGLOSC > 0)
	UNIQUE (NAZWA)
);
CREATE TABLE KONSTELACJE(
	NAZWA CHAR(255) PRIMARY KEY,
	REKTASCENSJA FLOAT CHECK (REKTASCENSJA >= 0 AND REKTASCENSJA <=24),
	DEKLINACJA FLOAT CHECK (DEKLINACJA >= -90 AND DEKLINACJA <= 90),
);
CREATE TABLE GALAKTYKI(
	NAZWA CHAR(255),
	TYP CHAR(10),
	CZY_JEST_KWAZAREM BIT,
	JASNOSC FLOAT CHECK (JASNOSC > 0),
	KONSTELACJA CHAR(255) REFERENCES KONSTELACJE(NAZWA),
	PRIMARY KEY(NAZWA),
	FOREIGN KEY(NAZWA) REFERENCES CIALA_NIEBIESKIE(NAZWA)
);
CREATE TABLE GWIAZDY(
	NAZWA CHAR(255),
	TYP CHAR(50),
	TYP_WIDMOWY CHAR(6),
	JASNOSC FLOAT CHECK (JASNOSC > 0),
	GWIAZDA CHAR(255) REFERENCES GWIAZDY(NAZWA),
	KONSTELACJA CHAR(255) REFERENCES KONSTELACJE(NAZWA),
	GALAKTYKA CHAR(255) REFERENCES GALAKTYKI(NAZWA),
	PRIMARY KEY(NAZWA),
	FOREIGN KEY(NAZWA) REFERENCES CIALA_NIEBIESKIE(NAZWA)
);
CREATE TABLE PLANETY(
	NAZWA CHAR(255),
	TYP CHAR(10) CHECK (TYP = 'Skalista' OR TYP = 'Gazowa'),
	NACHYLENIE_OSI FLOAT CHECK (NACHYLENIE_OSI >= 0 AND NACHYLENIE_OSI <= 90),
	OKRES_OBROTU FLOAT CHECK (OKRES_OBROTU > 0),
	OKRES_ORBITALNY FLOAT CHECK (OKRES_ORBITALNY > 0),
	GWIAZDA CHAR(255) REFERENCES GWIAZDY(NAZWA),
	PRIMARY KEY(NAZWA),
	FOREIGN KEY(NAZWA) REFERENCES CIALA_NIEBIESKIE(NAZWA)
);
CREATE TABLE KSIEZYCE(
	NAZWA CHAR(255),
	NACHYLENIE_OSI FLOAT CHECK (NACHYLENIE_OSI >= 0 AND NACHYLENIE_OSI <= 90),
	OKRES_OBROTU FLOAT CHECK (OKRES_OBROTU > 0),
	OKRES_ORBITALNY FLOAT CHECK (OKRES_ORBITALNY > 0),
	PLANETA CHAR(255) REFERENCES PLANETY(NAZWA),
	PRIMARY KEY(NAZWA),
	FOREIGN KEY(NAZWA) REFERENCES CIALA_NIEBIESKIE(NAZWA)
);
CREATE TABLE CZARNE_DZIURY(
	NAZWA CHAR(255),
	DYSK_AKRECYJNY BIT,
	LADUNEK_ELEKTRYCZNY BIT,
	MOMENT_PEDU BIT,
	KONSTELACJA CHAR(255) REFERENCES KONSTELACJE(NAZWA),
	GALAKTYKA CHAR(255) REFERENCES GALAKTYKI(NAZWA),
	CZARNA_DZIURA CHAR(255) REFERENCES CZARNE_DZIURY(NAZWA),
	PRIMARY KEY(NAZWA),
	FOREIGN KEY(NAZWA) REFERENCES CIALA_NIEBIESKIE(NAZWA)
);
CREATE TABLE PULSARY(
	NAZWA CHAR(255),
	OKRES_IMPULSU FLOAT CHECK (OKRES_IMPULSU >= 0.0014 AND OKRES_IMPULSU <= 8.5),
	CZESTOTLIWOSC_OBROTOW FLOAT CHECK (CZESTOTLIWOSC_OBROTOW > 0)
	PRIMARY KEY(NAZWA),
	FOREIGN KEY(NAZWA) REFERENCES GWIAZDY(NAZWA)
);
CREATE TABLE TELESKOPY(
	NAZWA CHAR(255) PRIMARY KEY,
	TYP CHAR(10) CHECK (TYP = 'Naziemny' OR TYP = 'Kosmiczny') NOT NULL,
	ORGANIZACJA CHAR(255) NOT NULL,
	POCZATEK_DZIA£ANIA DATE,
);
CREATE TABLE OBSERWACJE(
	ID_OBSERWACJI CHAR(13) CHECK (LEN(ID_OBSERWACJI) = 13) PRIMARY KEY NOT NULL,
	DATA_OBSERWACJI DATE NOT NULL,
	WYKONAWCA CHAR(100) NOT NULL,
	TELESKOP CHAR(255) REFERENCES TELESKOPY(NAZWA),
	CIALO_NIEBIESKIE CHAR(255) REFERENCES CIALA_NIEBIESKIE(NAZWA)
	UNIQUE (ID_OBSERWACJI)
);
CREATE TABLE ODKRYCIA(
	ID_ODKRYCIA CHAR(13) CHECK (LEN(ID_ODKRYCIA) = 13) PRIMARY KEY NOT NULL,
	DATA_ODKRYCIA DATE NOT NULL,
	WYKONAWCA CHAR(100) NOT NULL,
	TELESKOP CHAR(255) REFERENCES TELESKOPY(NAZWA),
	CIALO_NIEBIESKIE CHAR(255) REFERENCES CIALA_NIEBIESKIE(NAZWA)
	UNIQUE (ID_ODKRYCIA)
);